name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}
          # key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd ~/Deshi-Fresh-Bazar
            git pull origin main
            npm install
            npm run build
            pm2 restart all
